local cstyle = require 'common.cstyle'

-- Java-specific key commands.
local keys = _G.keys
if type(keys) == 'table' then
	keys.java = {}
end

keys.java = {
	al = {
		m = { io.open_file,
		(_HOME..'/modules/java/init.lua'):iconv('UTF-8', _CHARSET) },
	},
	['a\n'] = {cstyle.newline},
	['s\n'] = {cstyle.newline_semicolon},
	['c;'] = {cstyle.endline_semicolon},
	['}'] = {cstyle.match_brace_indent},
	['c{'] = {cstyle.openBraceMagic, true},
	['cM'] = {cstyle.selectScope},
	['\n'] = {cstyle.enter_key_pressed},
}

local snippets = _G.snippets

if type(snippets) == 'table' then
	snippets.java = {}
end

snippets.java = {
	boost = [[/*******************************************************************************
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/

%0]],
	gpl = [[/*******************************************************************************
 * Authors: %1(Your Name Here)
 * Copyright: %1
 * Date: %[date | cut -c 5-10] %[date | cut -c 25-]
 *
 * License:
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version
 * 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston,
 * MA 02111-1307, USA.
 ******************************************************************************/

%0]],
	gpl3 = [[/*******************************************************************************
 * Authors: %1(Your Name Here)
 * Copyright: %1(Your Name Here)
 * Date: %[date | cut -c 5-10] %[date | cut -c 25-]
 *
 * License:
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/

%0]],
	mit = [[/*******************************************************************************
 * The MIT License
 *
 * Copyright (c) %[date | cut -c 25-] %1(Your Name Here)
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 ******************************************************************************/

%0]],
	banner = [[/%<string.rep("*", buffer.edge_column - buffer.column[buffer.current_pos] - 1)>
 * %0
 %<string.rep("*", buffer.edge_column - buffer.column[buffer.current_pos] - 2)>/]],
	class = [[/**
 * @author %1
 */
public class %2(%<(buffer.filename or 'Untitled'):match('[^/\\]+$'):match('^[^%.]+')>) {
	%0
}
]],

	main = [[public static void main(String[] args) {
	%0
}]],
	sop = "System.out.println(%0);",
	sep = "System.err.println(%0);",
	pu = "public ",
	pr = "private ",
	pro = "protected ",
	package = [[package %1(%<((buffer.filename or ""):match(".+[/\\]") or ""):gsub("[/\\]",
		"."):gsub("^%.", ""):gsub("%.$", ""):gsub(".*com%.", "com.")>);]],
	pusf = [[public static final]],
	prsf = [[private static final]],
	st = [[String]],
	deb = [[LOG.debug(%0);]],
	err = [[LOG.error(%0);]],
	warn = [[LOG.warn(%0);]],
	inf = [[LOG.info(%0);]],
	comment = {
		auth = "@author ",
		pa = "@param ",
		re = "@return ",
	},
	supp = [[@SuppressWarnings("unchecked")]],
	vargs = [[private %1(type) %2(name);

public %1 get%4(%3<string.gsub("%2", "^%w", function(x) return string.upper(x) end)>)%() {
	return this.%2;
}

public void set%4%(final %1 %2) {
	this.%2 = %2;
}]],
	this = [[public %1(%<(buffer.filename or 'Untitled'):match('[^/\\]+$'):match('^[^%.]+')>)() {
}]]
}

return M
